-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.dim_campaign
(
    campaign_id character varying COLLATE pg_catalog."default" NOT NULL,
    channel_id character varying COLLATE pg_catalog."default",
    campaign_type character varying COLLATE pg_catalog."default",
    CONSTRAINT dim_campaign_pkey PRIMARY KEY (campaign_id)
);

CREATE TABLE IF NOT EXISTS public.dim_channel
(
    channel_id character varying COLLATE pg_catalog."default" NOT NULL,
    channel_name character varying COLLATE pg_catalog."default",
    platform character varying COLLATE pg_catalog."default",
    CONSTRAINT dim_channel_pkey PRIMARY KEY (channel_id)
);

CREATE TABLE IF NOT EXISTS public.dim_customer
(
    customer_id character varying COLLATE pg_catalog."default" NOT NULL,
    first_name character varying COLLATE pg_catalog."default",
    last_name character varying COLLATE pg_catalog."default",
    email character varying COLLATE pg_catalog."default",
    country character varying COLLATE pg_catalog."default",
    customer_type character varying COLLATE pg_catalog."default",
    CONSTRAINT dim_customer_pkey PRIMARY KEY (customer_id)
);

CREATE TABLE IF NOT EXISTS public.dim_date
(
    date_id integer NOT NULL,
    full_date date,
    year integer,
    month integer,
    day integer,
    quarter integer,
    month_name character varying(20) COLLATE pg_catalog."default",
    day_name character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT dim_date_pkey PRIMARY KEY (date_id)
);

CREATE TABLE IF NOT EXISTS public.dim_product
(
    product_id character varying COLLATE pg_catalog."default" NOT NULL,
    product_name character varying COLLATE pg_catalog."default",
    product_category character varying COLLATE pg_catalog."default",
    CONSTRAINT dim_product_pkey PRIMARY KEY (product_id)
);

CREATE TABLE IF NOT EXISTS public.fact_campaign_daily
(
    date_id integer NOT NULL,
    campaign_id character varying COLLATE pg_catalog."default",
    channel_id character varying COLLATE pg_catalog."default",
    impressions integer,
    clicks integer,
    spend numeric(12, 2),
    orders integer,
    revenue numeric(12, 2)
);

CREATE TABLE IF NOT EXISTS public.fact_order_items
(
    order_item_id character varying COLLATE pg_catalog."default",
    order_id character varying COLLATE pg_catalog."default",
    product_id character varying COLLATE pg_catalog."default",
    product_name character varying COLLATE pg_catalog."default",
    quantity integer,
    revenue numeric(12, 2)
);

CREATE TABLE IF NOT EXISTS public.fact_orders
(
    order_id character varying COLLATE pg_catalog."default",
    order_date_id integer,
    customer_id character varying COLLATE pg_catalog."default",
    channel_id character varying COLLATE pg_catalog."default",
    campaign_id character varying COLLATE pg_catalog."default",
    product_id character varying COLLATE pg_catalog."default",
    quantity integer,
    item_price numeric(12, 2),
    revenue numeric(12, 2)
);

ALTER TABLE IF EXISTS public.fact_campaign_daily
    ADD CONSTRAINT fk_fact_campaign_daily_dim_campaign FOREIGN KEY (campaign_id)
    REFERENCES public.dim_campaign (campaign_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fact_campaign_daily
    ADD CONSTRAINT fk_fact_campaign_daily_dim_channel FOREIGN KEY (channel_id)
    REFERENCES public.dim_channel (channel_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fact_campaign_daily
    ADD CONSTRAINT fk_fact_campaign_daily_dim_date FOREIGN KEY (date_id)
    REFERENCES public.dim_date (date_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fact_order_items
    ADD CONSTRAINT fk_fact_order_items_dim_product FOREIGN KEY (product_id)
    REFERENCES public.dim_product (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fact_orders
    ADD CONSTRAINT fk_fact_orders_dim_campaign FOREIGN KEY (campaign_id)
    REFERENCES public.dim_campaign (campaign_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fact_orders
    ADD CONSTRAINT fk_fact_orders_dim_channel FOREIGN KEY (channel_id)
    REFERENCES public.dim_channel (channel_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fact_orders
    ADD CONSTRAINT fk_fact_orders_dim_customer FOREIGN KEY (customer_id)
    REFERENCES public.dim_customer (customer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fact_orders
    ADD CONSTRAINT fk_fact_orders_dim_date FOREIGN KEY (order_date_id)
    REFERENCES public.dim_date (date_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fact_orders
    ADD CONSTRAINT fk_fact_orders_dim_product FOREIGN KEY (product_id)
    REFERENCES public.dim_product (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;